---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  namespace: local-cluster
  name: hub-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  clusterSet: hub-cluster
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  namespace: rhacm-rhacs-config
  name: hub-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  clusterSet: hub-cluster
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  namespace: rhacm-config
  name: hub-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  clusterSet: hub-cluster