---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: rhacs-config-local-cluster
  namespace: rhacm-rhacs-config
  labels:
    app: rhacm-rhacs-config
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  clusterSelector:
    matchLabels:
      local-cluster: 'true'