---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: set-default-sc
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: set-default-sc
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
  - apiGroups:
      - "storage.k8s.io"
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - exec
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: set-default-sc
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: set-default-sc
subjects:
  - kind: ServiceAccount
    name: set-default-sc
    namespace: openshift-storage
---
apiVersion: batch/v1
kind: Job
metadata:
  name: set-default-sc
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  template:
    spec:
      containers:
      - name: set-default-sc
        image: registry.redhat.io/openshift4/ose-cli:latest
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
          - -c
          - |
            #!/usr/bin/env bash

            until oc get storageclass ocs-storagecluster-ceph-rbd; do
                echo "Waiting for ocs-storagecluster-ceph-rbd StorageClass to be created"
                sleep 5
            done

            oc annotate --overwrite storageclass/ocs-storagecluster-ceph-rbd storageclass.kubernetes.io/is-default-class="true"

      serviceAccountName: set-default-sc
      restartPolicy: OnFailure