---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'release-2.9'
    target:
      kind: Subscription
      name: advanced-cluster-management