---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: netobserv-operator-group
  namespace: openshift-netobserv-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec: {}
