apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-storage-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "0"
spec:
  ignoreDifferences:
    - group: "*"
      kind: "*"
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
    - group: "v1"
      kind: "Namespace"
      jsonPointers:
        - /metadata/labels
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    kustomize:
      version: v5.1.0
    repoURL: 'https://github.com/kenmoini/ocp4-gitops-config.git'
    targetRevision: HEAD
    ## Path is the repo directory that containers the cluster(s) configuration and deployment manifests
    path: openshift/local-storage/operator/overlays/stable/
    #path: manifests/rhacm/operator/overlays/default/
    ## Enable recursive sub-directory search to enable management of multiple cluster from this single Application
    #directory:
    #  recurse: true
  project: local-cluster
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      # selfHeal: false # overrides changes made on the cluster that drift from git state