---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki-sb
  namespace: netobserv
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  objectBucketName: obc-netobserv-loki-sb
  bucketName: obc-netobserv-loki-sb
  storageClassName: openshift-storage.noobaa.io