---
apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: lso
  namespace: openshift-local-storage
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - storage.openshift.com/local-volume-protection
spec:
  deviceInclusionSpec:
    deviceTypes:
      - disk
      - part
    minSize: 1Gi
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - infra-1
              - infra-2
              - infra-3
  storageClassName: lso
  volumeMode: Block
  tolerations:
    - effect: NoSchedule
      key: node.ocs.openshift.io/storage
      operator: Equal
      value: 'true'
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      operator: Equal
      value: "reserved"
    - effect: NoExecute
      key: node-role.kubernetes.io/infra
      operator: Equal
      value: "reserved"
