---
apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeDiscovery
metadata:
  name: auto-discover-devices
  namespace: openshfit-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - infra-1
              - infra-2
              - infra-3
  tolerations:
    - effect: NoSchedule
      key: node.ocs.openshift.io/storage
      operator: Equal
      value: 'true'
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      operator: Equal
      value: "reserved"
    - effect: NoExecute
      key: node-role.kubernetes.io/infra
      operator: Equal
      value: "reserved"
