---
apiVersion: v1
kind: Namespace
metadata:
  name: rhacm-config
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: rhacm-rhacs-config
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "-1"